# Generated by Django 5.2.4 on 2025-07-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('skills', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField(default='Not Available')),
                ('score', models.FloatField()),
                ('matched_skills', models.TextField()),
            ],
        ),
    ]
