# Generated by Django 5.2.4 on 2025-07-22 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='experience',
            field=models.TextField(blank=True, default='Not Available'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
