# Generated by Django 5.2.4 on 2025-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screener', '0002_parsedresume_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='experience',
            field=models.TextField(default='Not Available'),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='matched_skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='skills',
            field=models.TextField(),
        ),
    ]
